apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-dcab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-dcab
    app.kubernetes.io/part-of: test-rhtap-70-app
  name: devfile-sample-code-with-quarkus-dcab
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-dcab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-dcab
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-70-tenant/test-rhtap-70-app/devfile-sample-code-with-quarkus-dcab@sha256:4858f09c1d74b9cb61a6594932e28305e6439f21e5bffe0576a8815b0b36f757
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
